const fs = require("fs");
const path = require("path");

const rootDir = path.resolve(__dirname, "..");
const sourcePath = path.join(rootDir, "src/data/menus.json");
const filterDatasetPath = path.join(rootDir, "src/data/menu-filter-dataset.json");

const VALID_SITUATION_TAGS = [
  "시간 없음",
  "해장 필요",
  "혼밥",
  "팀점심",
  "속 편하게",
  "매운 걸로",
  "국물 필요",
  "실패 금지",
  "미팅 전",
  "다이어트",
  "입맛 깨우기",
  "비 오는 날",
];

const VALID_CATEGORIES = ["한식", "중식", "일식", "양식", "분식", "아시안", "건강식"];
const VALID_BUDGET_TAGS = ["가볍게", "평범하게", "오늘은 써도 됨"];

const newMenus = [
  {
    id: "kr-041",
    name: "알탕",
    category: "한식",
    description: "톡톡 씹히는 알과 얼큰한 국물로 속을 빠르게 풀어주는 점심 메뉴입니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 12,
    calories: 650,
    healthy: false,
    meat: false,
    quick: true,
    spicy: true,
    ingredients: ["명란", "곤이", "무"],
    tags: ["soup", "seafood", "spicy"],
    rating: 4.5,
    baseLikes: 286,
    imageUrl: "https://source.unsplash.com/640x480/?spicy-fish-roe-soup,korean-food",
    spiceLevel: 2,
    soupLevel: 2,
    heaviness: 2,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 4,
    keywords: ["얼큰한 국물", "해장", "매콤", "혼밥 좋음"],
    avoidMoods: ["comfort", "meeting"],
  },
  {
    id: "kr-042",
    name: "대구탕",
    category: "한식",
    description: "맑고 시원한 생선 국물로 부담 없이 속을 데우는 탕 메뉴입니다.",
    priceLevel: "보통",
    price: 13000,
    prepMinutes: 13,
    calories: 520,
    healthy: true,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["대구", "무", "미나리"],
    tags: ["soup", "seafood", "light"],
    rating: 4.4,
    baseLikes: 238,
    imageUrl: "https://source.unsplash.com/640x480/?cod-fish-soup,korean-food",
    spiceLevel: 0,
    soupLevel: 2,
    heaviness: 1,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 2,
    hangoverFit: 4,
    keywords: ["맑은 국물", "해장", "가벼움", "부담 적음"],
    avoidMoods: ["spicy"],
  },
  {
    id: "kr-043",
    name: "고추장찌개",
    category: "한식",
    description: "칼칼한 고추장 국물과 감자가 밥 한 공기를 부르는 찌개입니다.",
    priceLevel: "저렴",
    price: 9000,
    prepMinutes: 11,
    calories: 620,
    healthy: false,
    meat: true,
    quick: true,
    spicy: true,
    ingredients: ["고추장", "감자", "돼지고기"],
    tags: ["soup", "rice", "spicy"],
    rating: 4.5,
    baseLikes: 304,
    imageUrl: "https://source.unsplash.com/640x480/?spicy-korean-stew",
    spiceLevel: 2,
    soupLevel: 2,
    heaviness: 2,
    speed: 2,
    priceTier: 1,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 2,
    hangoverFit: 3,
    keywords: ["매콤", "국물", "가성비", "밥심"],
    avoidMoods: ["comfort", "meeting"],
  },
  {
    id: "kr-044",
    name: "닭볶음탕",
    category: "한식",
    description: "매콤한 양념에 닭고기와 감자를 푸짐하게 끓인 팀 점심 후보입니다.",
    priceLevel: "보통",
    price: 13000,
    prepMinutes: 18,
    calories: 850,
    healthy: false,
    meat: true,
    quick: false,
    spicy: true,
    ingredients: ["닭고기", "감자", "고추장"],
    tags: ["stew", "meat", "spicy", "team"],
    rating: 4.6,
    baseLikes: 332,
    imageUrl: "https://source.unsplash.com/640x480/?dakbokkeumtang,korean-food",
    spiceLevel: 2,
    soupLevel: 1,
    heaviness: 3,
    speed: 1,
    priceTier: 2,
    soloFit: 2,
    teamFit: 4,
    meetingSafe: 1,
    hangoverFit: 2,
    keywords: ["매콤", "팀점심", "든든함", "밥심"],
    avoidMoods: ["noTime", "comfort", "meeting"],
  },
  {
    id: "kr-045",
    name: "물회",
    category: "한식",
    description: "차갑고 새콤매콤한 육수에 회와 채소를 말아 먹는 산뜻한 한 그릇입니다.",
    priceLevel: "보통",
    price: 14000,
    prepMinutes: 10,
    calories: 560,
    healthy: true,
    meat: false,
    quick: true,
    spicy: true,
    ingredients: ["회", "채소", "초고추장"],
    tags: ["seafood", "fresh", "spicy", "cold-soup"],
    rating: 4.4,
    baseLikes: 220,
    imageUrl: "https://source.unsplash.com/640x480/?korean-cold-seafood-soup",
    spiceLevel: 2,
    soupLevel: 1,
    heaviness: 1,
    speed: 3,
    priceTier: 2,
    soloFit: 3,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 2,
    keywords: ["산뜻함", "매콤", "가벼움", "졸림 방지"],
    avoidMoods: ["comfort", "meeting", "rainy"],
  },
  {
    id: "kr-046",
    name: "소머리국밥",
    category: "한식",
    description: "진한 국물과 고기로 오후까지 든든하게 버티는 국밥입니다.",
    priceLevel: "보통",
    price: 11000,
    prepMinutes: 8,
    calories: 760,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["소고기", "사골국물", "밥"],
    tags: ["soup", "rice", "meat"],
    rating: 4.6,
    baseLikes: 318,
    imageUrl: "https://source.unsplash.com/640x480/?korean-beef-soup,rice",
    spiceLevel: 0,
    soupLevel: 2,
    heaviness: 3,
    speed: 3,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 3,
    hangoverFit: 4,
    keywords: ["국물", "해장", "든든함", "빠름"],
    avoidMoods: ["spicy"],
  },
  {
    id: "cn-022",
    name: "탄탄면",
    category: "중식",
    description: "고소한 참깨 향과 얼큰한 국물이 같이 오는 중식 면 메뉴입니다.",
    priceLevel: "보통",
    price: 11000,
    prepMinutes: 10,
    calories: 760,
    healthy: false,
    meat: true,
    quick: true,
    spicy: true,
    ingredients: ["중화면", "돼지고기", "참깨소스"],
    tags: ["noodle", "soup", "spicy"],
    rating: 4.5,
    baseLikes: 294,
    imageUrl: "https://source.unsplash.com/640x480/?dan-dan-noodles",
    spiceLevel: 2,
    soupLevel: 1,
    heaviness: 2,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 2,
    keywords: ["매콤", "국물", "혼밥 좋음", "고소함"],
    avoidMoods: ["comfort", "meeting"],
  },
  {
    id: "cn-023",
    name: "굴짬뽕",
    category: "중식",
    description: "굴 향이 시원하게 올라오는 맑은 짬뽕으로 해장에 잘 맞습니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 10,
    calories: 680,
    healthy: false,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["굴", "중화면", "채소"],
    tags: ["noodle", "soup", "seafood"],
    rating: 4.4,
    baseLikes: 248,
    imageUrl: "https://source.unsplash.com/640x480/?oyster-noodle-soup",
    spiceLevel: 0,
    soupLevel: 2,
    heaviness: 1,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 2,
    hangoverFit: 4,
    keywords: ["맑은 국물", "해장", "가벼움", "혼밥 좋음"],
    avoidMoods: ["spicy", "meeting"],
  },
  {
    id: "cn-024",
    name: "짜장밥",
    category: "중식",
    description: "춘장 소스를 밥 위에 얹어 빠르고 익숙하게 먹기 좋은 메뉴입니다.",
    priceLevel: "저렴",
    price: 8000,
    prepMinutes: 7,
    calories: 690,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["춘장", "밥", "양파"],
    tags: ["rice", "quick", "solo"],
    rating: 4.3,
    baseLikes: 260,
    imageUrl: "https://source.unsplash.com/640x480/?black-bean-sauce-rice",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 2,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["가성비", "빠름", "혼밥 좋음", "무난함"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "cn-025",
    name: "딤섬정식",
    category: "중식",
    description: "여러 딤섬을 조금씩 먹는 가벼운 중식 정식입니다.",
    priceLevel: "프리미엄",
    price: 16000,
    prepMinutes: 14,
    calories: 620,
    healthy: false,
    meat: true,
    quick: false,
    spicy: false,
    ingredients: ["만두피", "새우", "돼지고기"],
    tags: ["set", "team", "premium"],
    rating: 4.5,
    baseLikes: 236,
    imageUrl: "https://source.unsplash.com/640x480/?dim-sum,lunch",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 1,
    speed: 1,
    priceTier: 3,
    soloFit: 2,
    teamFit: 4,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["팀점심", "가벼움", "프리미엄", "실패 낮음"],
    avoidMoods: ["spicy", "soup", "hangover", "noTime"],
  },
  {
    id: "jp-022",
    name: "마제소바",
    category: "일식",
    description: "국물 없이 비벼 먹는 진한 면 요리로 졸린 오후를 깨우기 좋습니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 10,
    calories: 780,
    healthy: false,
    meat: true,
    quick: true,
    spicy: true,
    ingredients: ["면", "다진고기", "부추"],
    tags: ["noodle", "spicy", "solo"],
    rating: 4.5,
    baseLikes: 306,
    imageUrl: "https://source.unsplash.com/640x480/?mazesoba,noodles",
    spiceLevel: 2,
    soupLevel: 0,
    heaviness: 2,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 1,
    keywords: ["매콤", "혼밥 좋음", "기분전환", "든든함"],
    avoidMoods: ["soup", "hangover", "comfort", "meeting"],
  },
  {
    id: "jp-023",
    name: "규카츠정식",
    category: "일식",
    description: "겉은 바삭하고 속은 부드러운 소고기 카츠 정식입니다.",
    priceLevel: "프리미엄",
    price: 17000,
    prepMinutes: 15,
    calories: 860,
    healthy: false,
    meat: true,
    quick: false,
    spicy: false,
    ingredients: ["소고기", "밥", "장국"],
    tags: ["set", "meat", "premium"],
    rating: 4.6,
    baseLikes: 278,
    imageUrl: "https://source.unsplash.com/640x480/?gyukatsu,japanese-food",
    spiceLevel: 0,
    soupLevel: 1,
    heaviness: 3,
    speed: 1,
    priceTier: 3,
    soloFit: 3,
    teamFit: 3,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["프리미엄", "든든함", "기분전환", "실패 낮음"],
    avoidMoods: ["spicy", "hangover", "noTime"],
  },
  {
    id: "jp-024",
    name: "사바시오야키정식",
    category: "일식",
    description: "소금으로 구운 고등어와 밥, 장국이 나오는 담백한 정식입니다.",
    priceLevel: "보통",
    price: 13000,
    prepMinutes: 12,
    calories: 690,
    healthy: true,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["고등어", "밥", "장국"],
    tags: ["fish", "set", "healthy"],
    rating: 4.4,
    baseLikes: 224,
    imageUrl: "https://source.unsplash.com/640x480/?grilled-mackerel,japanese-food",
    spiceLevel: 0,
    soupLevel: 1,
    heaviness: 1,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 1,
    keywords: ["담백함", "가벼움", "혼밥 좋음", "정식"],
    avoidMoods: ["spicy", "hangover", "meeting"],
  },
  {
    id: "ws-022",
    name: "봉골레파스타",
    category: "양식",
    description: "바지락과 올리브오일로 가볍게 먹기 좋은 파스타입니다.",
    priceLevel: "보통",
    price: 14000,
    prepMinutes: 13,
    calories: 650,
    healthy: false,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["바지락", "파스타면", "올리브오일"],
    tags: ["pasta", "seafood", "light"],
    rating: 4.4,
    baseLikes: 240,
    imageUrl: "https://source.unsplash.com/640x480/?vongole,pasta",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 1,
    speed: 2,
    priceTier: 2,
    soloFit: 3,
    teamFit: 3,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["가벼움", "기분전환", "무난함", "미팅 전"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "ws-023",
    name: "치킨필라프",
    category: "양식",
    description: "닭고기와 채소를 볶아 빠르게 먹기 좋은 밥 메뉴입니다.",
    priceLevel: "보통",
    price: 11000,
    prepMinutes: 9,
    calories: 720,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["닭고기", "밥", "채소"],
    tags: ["rice", "quick", "solo"],
    rating: 4.3,
    baseLikes: 232,
    imageUrl: "https://source.unsplash.com/640x480/?chicken-pilaf",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 2,
    speed: 3,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["빠름", "혼밥 좋음", "든든함", "무난함"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "ws-024",
    name: "잠봉뵈르",
    category: "양식",
    description: "바게트에 햄과 버터를 넣어 이동 중에도 깔끔하게 먹기 좋은 샌드위치입니다.",
    priceLevel: "보통",
    price: 10000,
    prepMinutes: 5,
    calories: 610,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["바게트", "햄", "버터"],
    tags: ["sandwich", "portable", "quick"],
    rating: 4.4,
    baseLikes: 218,
    imageUrl: "https://source.unsplash.com/640x480/?jambon-beurre,sandwich",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 1,
    speed: 3,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["빠름", "미팅 전", "가벼움"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "ff-017",
    name: "치킨너겟세트",
    category: "양식",
    description: "작게 집어 먹기 좋고 빠르게 나오는 치킨 사이드 세트입니다.",
    priceLevel: "저렴",
    price: 8500,
    prepMinutes: 5,
    calories: 720,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["치킨너겟", "감자튀김", "음료"],
    tags: ["fried", "fast", "portable"],
    rating: 4.2,
    baseLikes: 214,
    imageUrl: "https://source.unsplash.com/640x480/?chicken-nuggets,fast-food",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 2,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 2,
    hangoverFit: 1,
    keywords: ["빠름", "가성비", "혼밥 좋음"],
    avoidMoods: ["spicy", "soup", "hangover", "comfort"],
  },
  {
    id: "ff-018",
    name: "불고기피자",
    category: "양식",
    description: "달큰한 불고기 토핑으로 여럿이 나눠 먹기 좋은 피자입니다.",
    priceLevel: "보통",
    price: 14000,
    prepMinutes: 15,
    calories: 880,
    healthy: false,
    meat: true,
    quick: false,
    spicy: false,
    ingredients: ["도우", "불고기", "치즈"],
    tags: ["pizza", "team", "delivery"],
    rating: 4.4,
    baseLikes: 250,
    imageUrl: "https://source.unsplash.com/640x480/?bulgogi-pizza",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 3,
    speed: 1,
    priceTier: 2,
    soloFit: 2,
    teamFit: 4,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["팀점심", "든든함", "배달", "무난함"],
    avoidMoods: ["spicy", "soup", "hangover", "noTime"],
  },
  {
    id: "bs-021",
    name: "김치말이국수",
    category: "분식",
    description: "시원한 김치 국물과 소면으로 입맛을 가볍게 살리는 메뉴입니다.",
    priceLevel: "저렴",
    price: 8000,
    prepMinutes: 7,
    calories: 520,
    healthy: false,
    meat: false,
    quick: true,
    spicy: true,
    ingredients: ["소면", "김치", "육수"],
    tags: ["noodle", "cold-soup", "spicy"],
    rating: 4.3,
    baseLikes: 230,
    imageUrl: "https://source.unsplash.com/640x480/?kimchi-noodles",
    spiceLevel: 1,
    soupLevel: 1,
    heaviness: 1,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 2,
    hangoverFit: 2,
    keywords: ["빠름", "가성비", "국물", "산뜻함"],
    avoidMoods: ["meeting"],
  },
  {
    id: "bs-022",
    name: "참치마요김밥",
    category: "분식",
    description: "참치마요를 김밥에 말아 빠르고 든든하게 먹는 분식 메뉴입니다.",
    priceLevel: "저렴",
    price: 5500,
    prepMinutes: 5,
    calories: 520,
    healthy: false,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["김", "밥", "참치마요"],
    tags: ["kimbap", "portable", "quick"],
    rating: 4.4,
    baseLikes: 288,
    imageUrl: "https://source.unsplash.com/640x480/?kimbap,tuna",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 1,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["빠름", "가성비", "혼밥 좋음"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "as-020",
    name: "분보후에",
    category: "아시안",
    description: "얼큰한 베트남식 소고기 국수로 쌀국수보다 확실히 자극적입니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 10,
    calories: 690,
    healthy: false,
    meat: true,
    quick: true,
    spicy: true,
    ingredients: ["쌀국수", "소고기", "고추기름"],
    tags: ["noodle", "soup", "spicy"],
    rating: 4.5,
    baseLikes: 244,
    imageUrl: "https://source.unsplash.com/640x480/?bun-bo-hue,vietnamese-food",
    spiceLevel: 2,
    soupLevel: 2,
    heaviness: 2,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 1,
    hangoverFit: 4,
    keywords: ["얼큰한 국물", "해장", "매콤", "혼밥 좋음"],
    avoidMoods: ["comfort", "meeting"],
  },
  {
    id: "as-021",
    name: "카오카무",
    category: "아시안",
    description: "부드러운 족발 고기와 밥을 함께 먹는 태국식 덮밥입니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 11,
    calories: 760,
    healthy: false,
    meat: true,
    quick: true,
    spicy: false,
    ingredients: ["돼지고기", "밥", "간장소스"],
    tags: ["rice", "meat", "comfort"],
    rating: 4.3,
    baseLikes: 208,
    imageUrl: "https://source.unsplash.com/640x480/?khao-kha-moo,thai-food",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 2,
    speed: 2,
    priceTier: 2,
    soloFit: 4,
    teamFit: 2,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["밥심", "혼밥 좋음", "무난함", "든든함"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "hl-020",
    name: "단호박수프",
    category: "건강식",
    description: "부드럽고 따뜻한 단호박 수프로 속을 편하게 달래는 메뉴입니다.",
    priceLevel: "저렴",
    price: 9000,
    prepMinutes: 6,
    calories: 390,
    healthy: true,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["단호박", "우유", "크림"],
    tags: ["soup", "healthy", "soft"],
    rating: 4.2,
    baseLikes: 190,
    imageUrl: "https://source.unsplash.com/640x480/?pumpkin-soup",
    spiceLevel: 0,
    soupLevel: 2,
    heaviness: 0,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 1,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["속 편하게", "가벼움", "빠름", "국물"],
    avoidMoods: ["spicy"],
  },
  {
    id: "hl-021",
    name: "두부면파스타",
    category: "건강식",
    description: "두부면으로 탄수화물 부담을 줄인 가벼운 파스타입니다.",
    priceLevel: "보통",
    price: 12000,
    prepMinutes: 9,
    calories: 420,
    healthy: true,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["두부면", "토마토소스", "채소"],
    tags: ["healthy", "pasta", "light"],
    rating: 4.2,
    baseLikes: 184,
    imageUrl: "https://source.unsplash.com/640x480/?tofu-noodles,pasta",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 0,
    speed: 3,
    priceTier: 2,
    soloFit: 4,
    teamFit: 1,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["가벼움", "식단관리", "빠름", "미팅 전"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "lb-011",
    name: "샐러드도시락",
    category: "건강식",
    description: "채소와 단백질을 도시락 형태로 빠르게 챙기는 가벼운 점심입니다.",
    priceLevel: "저렴",
    price: 9000,
    prepMinutes: 4,
    calories: 430,
    healthy: true,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["채소", "달걀", "닭가슴살"],
    tags: ["lunchbox", "healthy", "portable"],
    rating: 4.3,
    baseLikes: 226,
    imageUrl: "https://source.unsplash.com/640x480/?salad-lunchbox",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 0,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 1,
    meetingSafe: 4,
    hangoverFit: 1,
    keywords: ["빠름", "가벼움", "식단관리"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
  {
    id: "lb-012",
    name: "불닭마요덮밥",
    category: "한식",
    description: "매운 닭고기와 마요가 밥 위에서 빠르게 힘을 주는 도시락 메뉴입니다.",
    priceLevel: "저렴",
    price: 8500,
    prepMinutes: 5,
    calories: 760,
    healthy: false,
    meat: true,
    quick: true,
    spicy: true,
    ingredients: ["닭고기", "마요네즈", "밥"],
    tags: ["rice", "spicy", "quick", "portable"],
    rating: 4.4,
    baseLikes: 270,
    imageUrl: "https://source.unsplash.com/640x480/?spicy-chicken-rice-bowl",
    spiceLevel: 3,
    soupLevel: 0,
    heaviness: 2,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 1,
    meetingSafe: 1,
    hangoverFit: 1,
    keywords: ["강한 매운맛", "빠름", "가성비"],
    avoidMoods: ["soup", "hangover", "comfort", "meeting"],
  },
  {
    id: "lb-013",
    name: "명란마요덮밥",
    category: "한식",
    description: "짭짤한 명란과 마요로 빠르게 먹기 좋은 고소한 덮밥입니다.",
    priceLevel: "저렴",
    price: 9000,
    prepMinutes: 5,
    calories: 680,
    healthy: false,
    meat: false,
    quick: true,
    spicy: false,
    ingredients: ["명란", "마요네즈", "밥"],
    tags: ["rice", "quick", "portable"],
    rating: 4.3,
    baseLikes: 234,
    imageUrl: "https://source.unsplash.com/640x480/?mentaiko-rice-bowl",
    spiceLevel: 0,
    soupLevel: 0,
    heaviness: 1,
    speed: 3,
    priceTier: 1,
    soloFit: 4,
    teamFit: 1,
    meetingSafe: 3,
    hangoverFit: 1,
    keywords: ["빠름", "가성비", "혼밥 좋음"],
    avoidMoods: ["spicy", "soup", "hangover"],
  },
];

const topGeneratedMenus = [
  {
    id: "top-001",
    name: "뚝배기불고기",
    category: "한식",
    description: "달달한 간장 양념과 당면을 자작한 국물로 즐기는 1인 뚝배기 메뉴입니다.",
    situation_tags: ["속 편하게", "혼밥", "미팅 전", "국물 필요"],
    budget_tag: "평범하게",
  },
  {
    id: "top-002",
    name: "추어탕",
    category: "한식",
    description: "걸쭉하고 진한 국물로 기운이 없을 때 찾기 좋은 보양식입니다.",
    situation_tags: ["속 편하게", "국물 필요", "해장 필요"],
    budget_tag: "평범하게",
  },
  {
    id: "top-003",
    name: "동태찌개",
    category: "한식",
    description: "시원하고 칼칼한 생선 국물로 속을 뚫어주는 찌개입니다.",
    situation_tags: ["해장 필요", "국물 필요", "비 오는 날"],
    budget_tag: "평범하게",
  },
  {
    id: "top-004",
    name: "낙지비빔밥",
    category: "한식",
    description: "매콤하게 볶은 낙지와 콩나물을 밥에 비벼 먹는 점심 스태미나 메뉴입니다.",
    situation_tags: ["매운 걸로", "실패 금지", "혼밥", "입맛 깨우기"],
    budget_tag: "평범하게",
  },
  {
    id: "top-005",
    name: "한식뷔페",
    category: "한식",
    description: "매일 바뀌는 반찬으로 메뉴 고민을 줄여주는 직장인 점심 선택지입니다.",
    situation_tags: ["시간 없음", "혼밥", "팀점심", "실패 금지"],
    budget_tag: "가볍게",
  },
  {
    id: "top-006",
    name: "소불고기전골",
    category: "한식",
    description: "달달한 국물에 소고기, 당면, 버섯을 끓여 먹는 팀 점심 메뉴입니다.",
    situation_tags: ["팀점심", "미팅 전", "국물 필요", "실패 금지"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-007",
    name: "매운갈비찜",
    category: "한식",
    description: "부드러운 갈비와 화끈한 양념으로 스트레스를 풀기 좋은 메뉴입니다.",
    situation_tags: ["매운 걸로", "입맛 깨우기", "팀점심"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-008",
    name: "보리밥정식",
    category: "한식",
    description: "강된장과 나물을 넣고 비벼 먹는 속 편한 토속 점심입니다.",
    situation_tags: ["속 편하게", "혼밥", "실패 금지"],
    budget_tag: "가볍게",
  },
  {
    id: "top-009",
    name: "간짜장",
    category: "중식",
    description: "즉석에서 볶아낸 춘장과 아삭한 양파 식감이 살아 있는 중식 메뉴입니다.",
    situation_tags: ["혼밥", "실패 금지"],
    budget_tag: "평범하게",
  },
  {
    id: "top-010",
    name: "꿔바로우",
    category: "중식",
    description: "쫀득하고 바삭한 튀김에 새콤달콤한 소스를 입힌 중식 사이드 메뉴입니다.",
    situation_tags: ["실패 금지", "팀점심"],
    budget_tag: "평범하게",
  },
  {
    id: "top-011",
    name: "울면",
    category: "중식",
    description: "걸쭉하고 담백한 국물로 자극 없이 먹기 좋은 중식 면 요리입니다.",
    situation_tags: ["속 편하게", "국물 필요", "해장 필요"],
    budget_tag: "평범하게",
    ingredients: ["면", "달걀", "채소", "전분 국물"],
    tags: ["noodle", "soup", "light"],
    keywords: ["걸쭉한 국물", "부담 적음", "중식 면", "속 편함"],
  },
  {
    id: "top-012",
    name: "짬뽕밥",
    category: "중식",
    description: "얼큰한 짬뽕 국물에 밥을 말아 든든하게 해장하는 메뉴입니다.",
    situation_tags: ["해장 필요", "국물 필요", "비 오는 날", "매운 걸로"],
    budget_tag: "평범하게",
  },
  {
    id: "top-013",
    name: "중화냉면",
    category: "중식",
    description: "차가운 육수와 땅콩소스가 어우러지는 여름철 별미 중식입니다.",
    situation_tags: ["속 편하게", "시간 없음", "혼밥"],
    budget_tag: "평범하게",
  },
  {
    id: "top-014",
    name: "소유라멘",
    category: "일식",
    description: "깔끔한 간장 육수와 차슈를 곁들인 부담 적은 라멘입니다.",
    situation_tags: ["국물 필요", "비 오는 날", "혼밥"],
    budget_tag: "평범하게",
  },
  {
    id: "top-015",
    name: "회덮밥",
    category: "일식",
    description: "신선한 회와 채소, 초고추장을 밥에 비벼 먹는 산뜻한 덮밥입니다.",
    situation_tags: ["속 편하게", "미팅 전", "혼밥", "입맛 깨우기"],
    budget_tag: "평범하게",
  },
  {
    id: "top-016",
    name: "김치나베돈카츠",
    category: "일식",
    description: "김치 국물에 돈카츠를 자작하게 졸여 느끼함을 잡은 메뉴입니다.",
    situation_tags: ["국물 필요", "매운 걸로", "비 오는 날"],
    budget_tag: "평범하게",
    ingredients: ["돈카츠", "김치", "달걀", "밥"],
    tags: ["katsu", "soup", "spicy", "rice"],
    heaviness: 2,
    keywords: ["매콤", "국물", "돈카츠", "비 오는 날"],
  },
  {
    id: "top-017",
    name: "알밥",
    category: "일식",
    description: "뚝배기에서 톡톡 터지는 날치알과 누룽지를 즐기는 빠른 한 그릇입니다.",
    situation_tags: ["시간 없음", "혼밥"],
    budget_tag: "가볍게",
  },
  {
    id: "top-018",
    name: "수제버거",
    category: "양식",
    description: "육즙 있는 패티와 신선한 채소를 넣은 든든한 프리미엄 버거입니다.",
    situation_tags: ["실패 금지", "혼밥"],
    budget_tag: "평범하게",
  },
  {
    id: "top-019",
    name: "경양식돈까스",
    category: "양식",
    description: "얇게 편 고기에 달큰한 브라운 소스를 얹은 추억의 돈까스입니다.",
    situation_tags: ["실패 금지", "팀점심"],
    budget_tag: "가볍게",
  },
  {
    id: "top-020",
    name: "화덕피자",
    category: "양식",
    description: "담백하게 구운 도우와 토핑을 나눠 먹기 좋은 피자 메뉴입니다.",
    situation_tags: ["속 편하게", "팀점심"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-021",
    name: "샌드위치&스프",
    category: "건강식",
    description: "샌드위치와 따뜻한 스프로 가볍고 빠르게 채우는 점심 세트입니다.",
    situation_tags: ["시간 없음", "혼밥", "속 편하게"],
    budget_tag: "가볍게",
  },
  {
    id: "top-022",
    name: "떡튀순세트",
    category: "분식",
    description: "떡볶이, 튀김, 순대를 한 번에 먹는 분식 대표 조합입니다.",
    situation_tags: ["매운 걸로", "팀점심", "비 오는 날"],
    budget_tag: "가볍게",
    ingredients: ["떡볶이", "튀김", "순대"],
    tags: ["bunsik", "spicy", "team"],
    soupLevel: 0,
    hangoverFit: 1,
    keywords: ["분식", "매콤", "팀점심", "가성비"],
    avoidMoods: ["soup", "hangover", "comfort", "meeting"],
  },
  {
    id: "top-023",
    name: "프랜차이즈버거세트",
    category: "양식",
    description: "빠르게 주문하고 빠르게 먹을 수 있는 대표적인 점심 타임세이버입니다.",
    situation_tags: ["시간 없음", "혼밥", "실패 금지"],
    budget_tag: "가볍게",
  },
  {
    id: "top-024",
    name: "수제비",
    category: "분식",
    description: "쫀득한 반죽을 뜯어 넣은 따뜻한 국물 메뉴입니다.",
    situation_tags: ["국물 필요", "비 오는 날", "속 편하게"],
    budget_tag: "가볍게",
  },
  {
    id: "top-025",
    name: "한솥도시락",
    category: "한식",
    description: "검증된 구성의 따뜻한 도시락으로 빠르게 점심을 해결하기 좋습니다.",
    situation_tags: ["시간 없음", "혼밥"],
    budget_tag: "가볍게",
  },
  {
    id: "top-026",
    name: "닭가슴살볶음밥",
    category: "건강식",
    description: "단백질과 탄수화물을 간단히 챙기는 식단관리용 볶음밥입니다.",
    situation_tags: ["시간 없음", "혼밥", "속 편하게"],
    budget_tag: "가볍게",
  },
  {
    id: "top-027",
    name: "샤브샤브",
    category: "건강식",
    description: "채소와 고기를 국물에 데쳐 먹는 깔끔하고 건강한 점심 메뉴입니다.",
    situation_tags: ["속 편하게", "국물 필요", "팀점심"],
    budget_tag: "평범하게",
  },
  {
    id: "top-028",
    name: "샤브샤브죽",
    category: "한식",
    description: "샤브샤브 국물에 밥을 넣어 부드럽게 마무리하는 속 편한 메뉴입니다.",
    situation_tags: ["속 편하게", "국물 필요", "혼밥"],
    budget_tag: "평범하게",
  },
  {
    id: "top-029",
    name: "묵밥",
    category: "건강식",
    description: "도토리묵과 밥을 시원한 육수에 말아 먹는 가볍고 담백한 메뉴입니다.",
    situation_tags: ["속 편하게", "혼밥", "다이어트"],
    budget_tag: "가볍게",
  },
  {
    id: "top-030",
    name: "장어덮밥",
    category: "일식",
    description: "윤기 나는 장어구이를 밥 위에 올린 프리미엄 보양 덮밥입니다.",
    situation_tags: ["실패 금지", "혼밥", "미팅 전"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-031",
    name: "한우구이정식",
    category: "한식",
    description: "한우 구이와 정갈한 반찬으로 점심을 확실히 끌어올리는 메뉴입니다.",
    situation_tags: ["팀점심", "실패 금지", "미팅 전"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-032",
    name: "대게정식",
    category: "한식",
    description: "대게살과 곁들임을 천천히 즐기는 법카 감성의 특별 점심입니다.",
    situation_tags: ["팀점심", "실패 금지"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-033",
    name: "스페셜초밥",
    category: "일식",
    description: "좋은 생선 구성을 한 번에 즐기는 조금 더 근사한 초밥 세트입니다.",
    situation_tags: ["속 편하게", "미팅 전", "실패 금지"],
    budget_tag: "오늘은 써도 됨",
  },
  {
    id: "top-034",
    name: "참치회덮밥",
    category: "일식",
    description: "참치와 채소를 산뜻하게 비벼 먹는 깔끔한 프리미엄 회덮밥입니다.",
    situation_tags: ["속 편하게", "혼밥", "다이어트"],
    budget_tag: "오늘은 써도 됨",
  },
];

newMenus.push(...topGeneratedMenus.map(createMenuFromTopMenu));

function hasTag(menu, values) {
  return values.some((value) => menu.tags?.includes(value));
}

function hasKeyword(menu, values) {
  return values.some((value) => menu.keywords?.includes(value));
}

function createMenuFromTopMenu(menu) {
  const manualTags = cleanSituationTags(menu.situation_tags);
  const category = normalizeCategory(menu);
  const price = getPriceFromBudgetTag(menu.budget_tag);
  const isSpicy = manualTags.includes("매운 걸로");
  const needsSoup = manualTags.includes("국물 필요") || manualTags.includes("해장 필요") || manualTags.includes("비 오는 날");
  const isFast = manualTags.includes("시간 없음");
  const isComfort = manualTags.includes("속 편하게");
  const isDiet = category === "건강식" || manualTags.includes("다이어트");
  const isPremium = menu.budget_tag === "오늘은 써도 됨";
  const categoryTags = getCategoryTags(category);
  const englishTags = [
    ...categoryTags,
    isSpicy ? "spicy" : "",
    needsSoup ? "soup" : "",
    isFast ? "quick" : "",
    manualTags.includes("팀점심") ? "team" : "",
    isPremium ? "premium" : "",
    isComfort ? "light" : "",
  ].filter(Boolean);

  return {
    id: menu.id,
    name: menu.name,
    category,
    description: menu.description,
    priceLevel: menu.budget_tag === "가볍게" ? "저렴" : menu.budget_tag === "오늘은 써도 됨" ? "프리미엄" : "보통",
    price,
    prepMinutes: isFast ? 7 : manualTags.includes("팀점심") ? 14 : 11,
    calories: getDefaultCalories(category, manualTags),
    healthy: isDiet,
    meat: /고기|소|돼지|닭|갈비|불고기|돈|카츠|버거|찜닭|제육/.test(menu.name + menu.description),
    quick: isFast,
    spicy: isSpicy,
    ingredients: menu.ingredients || getDefaultIngredients(menu.name),
    tags: [...new Set(menu.tags || englishTags)],
    rating: manualTags.includes("실패 금지") ? 4.6 : 4.4,
    baseLikes: manualTags.includes("실패 금지") ? 300 : manualTags.includes("팀점심") ? 270 : 240,
    imageUrl: `https://source.unsplash.com/640x480/?${encodeURIComponent(menu.name)},lunch`,
    spiceLevel: isSpicy ? 2 : 0,
    soupLevel: menu.soupLevel ?? (needsSoup ? 2 : 0),
    heaviness: menu.heaviness ?? (isDiet || isComfort ? 1 : manualTags.includes("팀점심") || isPremium ? 2 : 1),
    speed: isFast ? 3 : 2,
    priceTier: menu.budget_tag === "가볍게" ? 1 : menu.budget_tag === "오늘은 써도 됨" ? 3 : 2,
    soloFit: manualTags.includes("혼밥") || isFast ? 4 : 2,
    teamFit: manualTags.includes("팀점심") ? 4 : 2,
    meetingSafe: manualTags.includes("미팅 전") || isComfort ? 4 : isSpicy ? 1 : 3,
    hangoverFit: menu.hangoverFit ?? (manualTags.includes("해장 필요") ? 4 : needsSoup ? 2 : 1),
    keywords: menu.keywords || getKeywordsFromSituationTags(manualTags),
    avoidMoods: menu.avoidMoods || getAvoidMoodsFromSituationTags(manualTags),
    top_situation_tags: manualTags,
  };
}

function cleanSituationTags(tags = []) {
  const mapped = tags.flatMap((tag) => {
    if (tag === "건강식") return ["속 편하게", "미팅 전", "다이어트"];
    if (tag === "도시락") return ["시간 없음", "혼밥"];
    if (tag === "이동 최소화") return ["시간 없음"];
    if (tag === "졸림 주의") return ["입맛 깨우기"];
    if (tag === "월급 전") return [];
    return [tag];
  });
  return VALID_SITUATION_TAGS.filter((tag) => mapped.includes(tag));
}

function normalizeCategory(menu) {
  if (menu.category === "패스트푸드") return "양식";
  if (menu.category !== "도시락") return menu.category;

  if (/(샐러드|현미|닭가슴살)/.test(menu.name)) return "건강식";
  if (/(돈까스|명란|카레)/.test(menu.name)) return "일식";
  if (/(햄버그|버거)/.test(menu.name)) return "양식";
  return "한식";
}

function getPriceFromBudgetTag(budgetTag) {
  if (budgetTag === "가볍게") return 8500;
  if (budgetTag === "오늘은 써도 됨") return 16000;
  return 12000;
}

function getCategoryTags(category) {
  const tagsByCategory = {
    한식: ["rice"],
    중식: ["rice"],
    일식: ["rice"],
    양식: ["western"],
    분식: ["quick"],
    아시안: ["asian"],
    건강식: ["healthy", "light"],
  };
  return tagsByCategory[category] || [];
}

function getDefaultCalories(category, situationTags) {
  if (situationTags.includes("다이어트")) return 520;
  if (category === "건강식") return 480;
  if (situationTags.includes("국물 필요")) return 620;
  if (situationTags.includes("팀점심")) return 820;
  return 680;
}

function getDefaultIngredients(name) {
  const compactName = name.replace(/[()/&]/g, " ").split(/\s+/).filter(Boolean)[0] || name;
  return [compactName, "밥", "채소"];
}

function getKeywordsFromSituationTags(tags) {
  const keywordMap = {
    "시간 없음": "빠름",
    "해장 필요": "해장",
    혼밥: "혼밥 좋음",
    팀점심: "팀점심",
    "속 편하게": "부담 적음",
    "매운 걸로": "매콤",
    "국물 필요": "국물",
    "실패 금지": "실패 낮음",
    "미팅 전": "미팅 전",
    다이어트: "식단관리",
    "입맛 깨우기": "기분전환",
    "비 오는 날": "비 오는 날",
  };
  return tags.map((tag) => keywordMap[tag]).filter(Boolean);
}

function getAvoidMoodsFromSituationTags(tags) {
  const avoid = [];
  if (!tags.includes("매운 걸로")) avoid.push("spicy");
  if (!tags.includes("국물 필요") && !tags.includes("해장 필요")) avoid.push("soup", "hangover");
  if (tags.includes("매운 걸로")) avoid.push("comfort", "meeting");
  return [...new Set(avoid)];
}

function normalizeKeywords(keywords = []) {
  return [...new Set(keywords.map((keyword) => (keyword === "이동 최소화" ? "빠름" : keyword)))];
}

function normalizeAvoidMoods(avoidMoods = []) {
  return [...new Set(avoidMoods.filter((mood) => mood !== "paydayBefore"))];
}

function getBudgetTag(menu) {
  if (typeof menu.price === "number") {
    if (menu.price < 10000) return "가볍게";
    if (menu.price >= 15000) return "오늘은 써도 됨";
    return "평범하게";
  }
  if (menu.priceTier === 1 || menu.priceLevel === "저렴") return "가볍게";
  if (menu.priceTier === 3 || menu.priceLevel === "프리미엄") return "오늘은 써도 됨";
  if (menu.priceTier === 2 || menu.priceLevel === "보통") return "평범하게";
  return "상관없음";
}

function deriveSituationTags(menu) {
  const tags = [];
  const add = (tag, condition) => {
    if (condition) tags.push(tag);
  };
  const isFast = menu.speed >= 3 || menu.prepMinutes <= 8 || hasTag(menu, ["fast", "quick", "portable", "sandwich", "burger", "wrap", "kimbap"]);

  add("시간 없음", isFast);
  add("해장 필요", menu.hangoverFit >= 3 || (menu.soupLevel >= 2 && menu.spiceLevel >= 1));
  add("혼밥", menu.soloFit >= 3 || hasTag(menu, ["solo", "quick", "portable"]));
  add("팀점심", menu.teamFit >= 3 || hasTag(menu, ["team", "set", "pizza"]));
  add(
    "속 편하게",
    menu.spiceLevel <= 1 &&
      menu.heaviness <= 1 &&
      (menu.healthy || menu.meetingSafe >= 3 || hasTag(menu, ["soft", "light", "healthy"])) &&
      !hasTag(menu, ["fried", "spicy"]),
  );
  add("다이어트", menu.category === "건강식" || hasKeyword(menu, ["식단관리"]) || (menu.healthy && menu.heaviness <= 1 && menu.calories <= 650 && !hasTag(menu, ["fried"])));
  add("매운 걸로", menu.spiceLevel >= 2 || hasTag(menu, ["spicy"]));
  add("국물 필요", menu.soupLevel >= 1 || hasTag(menu, ["soup", "stew", "broth", "ramen", "hotpot"]));
  add("실패 금지", menu.meetingSafe >= 3 || menu.rating >= 4.6 || hasKeyword(menu, ["실패 낮음", "무난함"]));
  add(
    "미팅 전",
    menu.meetingSafe >= 3 &&
      menu.spiceLevel <= 1 &&
      menu.heaviness <= 2 &&
      !hasTag(menu, ["fish", "seafood", "fried", "spicy"]),
  );
  add("입맛 깨우기", menu.spiceLevel >= 2 || hasTag(menu, ["curry", "fresh"]) || hasKeyword(menu, ["산뜻함", "기분전환"]));
  add("비 오는 날", menu.soupLevel >= 1 || hasTag(menu, ["soup", "stew", "ramen", "hotpot"]) || hasKeyword(menu, ["국물", "얼큰한 국물"]));

  return VALID_SITUATION_TAGS.filter((tag) => tags.includes(tag));
}

function validateMenu(menu) {
  if (!VALID_CATEGORIES.includes(menu.category)) {
    throw new Error(`${menu.name}: invalid category ${menu.category}`);
  }

  const budgetTag = getBudgetTag(menu);
  if (!VALID_BUDGET_TAGS.includes(budgetTag)) {
    throw new Error(`${menu.name}: invalid budget tag ${budgetTag}`);
  }

  const invalidSituationTag = [...deriveSituationTags(menu), ...cleanSituationTags(menu.top_situation_tags)].find((tag) => !VALID_SITUATION_TAGS.includes(tag));
  if (invalidSituationTag) {
    throw new Error(`${menu.name}: invalid situation tag ${invalidSituationTag}`);
  }
}

function mergeSituationTags(derivedTags, manualTags = []) {
  const merged = new Set([...derivedTags, ...cleanSituationTags(manualTags)]);
  return VALID_SITUATION_TAGS.filter((tag) => merged.has(tag));
}

const sourceMenus = JSON.parse(fs.readFileSync(sourcePath, "utf8"));
const newMenuByName = new Map(newMenus.map((menu) => [menu.name, menu]));
const existingNames = new Set(sourceMenus.map((menu) => menu.name));
const additions = newMenus.filter((menu) => !existingNames.has(menu.name));
const mergedMenus = [
  ...sourceMenus.map((menu) => (newMenuByName.has(menu.name) ? { ...menu, ...newMenuByName.get(menu.name) } : menu)),
  ...additions,
];

const normalizedMenus = mergedMenus.map((menu) => {
  const normalizedMenu = { ...menu, category: normalizeCategory(menu) };
  validateMenu(normalizedMenu);
  const { top_situation_tags: topSituationTags, ...menuFields } = normalizedMenu;
  return {
    ...menuFields,
    keywords: normalizeKeywords(menuFields.keywords),
    avoidMoods: normalizeAvoidMoods(menuFields.avoidMoods),
    situation_tags: mergeSituationTags(deriveSituationTags(normalizedMenu), topSituationTags),
    budget_tag: getBudgetTag(normalizedMenu),
  };
});

const filterDataset = normalizedMenus.map((menu, index) => ({
  id: index + 1,
  name: menu.name,
  category: menu.category,
  description: menu.description,
  situation_tags: menu.situation_tags,
  budget_tag: menu.budget_tag,
}));

fs.writeFileSync(sourcePath, `${JSON.stringify(normalizedMenus, null, 2)}\n`);
fs.writeFileSync(filterDatasetPath, `${JSON.stringify(filterDataset, null, 2)}\n`);

console.log(`updated menus: ${sourceMenus.length} -> ${normalizedMenus.length}`);
console.log(`added menus: ${additions.length}`);
console.log(`filter dataset: ${path.relative(rootDir, filterDatasetPath)}`);
