module.exports = [
  {
    id: "jp-004",
    name: "가츠동",
    filename: "katsudon",
    reason: "밥 위에 달걀과 양파로 조린 돈카츠가 분명하게 보이는 가츠동 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "ws-006",
    name: "스테이크덮밥",
    filename: "steak-rice-bowl",
    reason: "밥 위에 먹기 좋게 썬 스테이크와 채소가 올라간 덮밥 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "ws-008",
    name: "치킨스테이크",
    filename: "chicken-steak",
    reason: "완전히 익은 닭고기 속살과 노릇한 껍질이 분명한 치킨스테이크 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "as-012",
    name: "케밥라이스",
    filename: "kebab-rice",
    reason: "밥과 구운 케밥 고기, 채소, 흰 소스 구성이 풍성하게 보이는 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "hl-009",
    name: "곤약면샐러드",
    filename: "konjac-noodle-salad",
    reason: "투명한 곤약면과 다채로운 채소가 선명하게 구분되는 샐러드 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "jp-017",
    name: "연어구이정식",
    filename: "grilled-salmon-set",
    reason: "연어구이와 밥, 미소국, 반찬이 밝고 정갈하게 보이는 정식 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "hl-016",
    name: "샐러드랩",
    filename: "salad-wrap",
    reason: "닭고기와 채소가 가득한 랩 단면이 선명하게 보이는 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "top-025",
    name: "한솥도시락",
    filename: "hansot-lunchbox",
    reason: "밥과 고기 반찬, 튀김, 달걀, 김치가 칸별로 담긴 따뜻한 도시락 사진",
    reviewedAt: "2026-07-21",
  },
  {
    id: "top-030",
    name: "장어덮밥",
    filename: "unagi-don",
    reason: "윤기와 구운 결이 살아 있는 장어가 밥 위를 가득 덮은 밝은 사진",
    reviewedAt: "2026-07-21",
  },
];
